name: Deploy GitHub Pages

# Dispara em push na branch main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do seu código
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # 2. (Opcional) Instala dependências ou roda build se você tiver pré-processamento
      # - name: Build estático
      #   run: npm ci && npm run build

      # 3. Garante que o .nojekyll está presente
      - name: Cria .nojekyll se não existir
        run: |
          PUBLISH_DIR=./docs
          # Ajuste para ./ se você publica da raiz
          if [ ! -f "$PUBLISH_DIR/.nojekyll" ]; then
            touch "$PUBLISH_DIR/.nojekyll"
          fi

      # 4. Deploy para a branch gh-pages
      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Pode usar GITHUB_TOKEN se tiver permissão Read & Write
         github_token: ${{ secrets.GITHUB_TOKEN }}  # ou ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # ou ./ se seu index.html estiver na raiz
          publish_branch: gh-pages  # branch onde o site será publicado
          keep_files: false         # remove arquivos antigos antes de publicar

